#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# npm test
# npx --no-install commitlint --edit "$1"
echo 'commiting'
# yarn lint-staged

# pnpm test
npx lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

